// Auth action types

export enum AuthActionTypes {
  LOGIN_REQUESTED = '@auth/LOGIN_REQUESTED',
  LOGIN_LOADING = '@auth/LOGIN_LOADING',
  LOGIN_FAILURE = '@auth/LOGIN_FAILURE',
  LOGIN_SUCCESS = '@auth/LOGIN_SUCCESS',

  REGISTER_REQUESTED = '@auth/REGISTER_REQUESTED',
  REGISTER_LOADING = '@auth/REGISTER_LOADING',
  REGISTER_FAILURE = '@auth/REGISTER_FAILURE',
  REGISTER_SUCCESS = '@auth/REGISTER_SUCCESS',

  SET_REGISTER_FORM_IS_DIRTY = '@auth/SET_REGISTER_FORM_IS_DIRTY',
}
