// Phrasebook action types

export enum PhrasebookActionTypes {
  FETCH_PHRASE_CATEGORY_LIST_REQUESTED = '@phrasebook/FETCH_PHRASE_CATEGORY_LIST_REQUESTED',
  FETCH_PHRASE_CATEGORY_LIST_LOADING = '@phrasebook/FETCH_PHRASE_CATEGORY_LIST_LOADING',
  FETCH_PHRASE_CATEGORY_LIST_FAILURE = '@phrasebook/FETCH_PHRASE_CATEGORY_LIST_FAILURE',
  FETCH_PHRASE_CATEGORY_LIST_SUCCESS = '@phrasebook/FETCH_PHRASE_CATEGORY_LIST_SUCCESS',

  SET_PHRASE_FORM_IS_DIRTY = '@phrasebook/SET_PHRASE_FORM_IS_DIRTY',
}
