// Phrasebook action types

export enum PhrasebookActionTypes {
  FETCH_PHRASE_CATEGORY_LIST_REQUESTED = '@phrasebook/FETCH_PHRASE_CATEGORY_LIST_REQUESTED',
  FETCH_PHRASE_CATEGORY_LIST_LOADING = '@phrasebook/FETCH_PHRASE_CATEGORY_LIST_LOADING',
  FETCH_PHRASE_CATEGORY_LIST_FAILURE = '@phrasebook/FETCH_PHRASE_CATEGORY_LIST_FAILURE',
  FETCH_PHRASE_CATEGORY_LIST_SUCCESS = '@phrasebook/FETCH_PHRASE_CATEGORY_LIST_SUCCESS',

  CREATE_PHRASE_REQUESTED = '@phrasebook/CREATE_PHRASE_REQUESTED',
  CREATE_PHRASE_LOADING = '@phrasebook/CREATE_PHRASE_LOADING',
  CREATE_PHRASE_FAILURE = '@phrasebook/CREATE_PHRASE_FAILURE',
  CREATE_PHRASE_SUCCESS = '@phrasebook/CREATE_PHRASE_SUCCESS',

  FETCH_PHRASE_LIST_REQUESTED = '@phrasebook/FETCH_PHRASE_LIST_REQUESTED',
  FETCH_PHRASE_LIST_LOADING = '@phrasebook/FETCH_PHRASE_LIST_LOADING',
  FETCH_PHRASE_LIST_FAILURE = '@phrasebook/FETCH_PHRASE_LIST_FAILURE',
  FETCH_PHRASE_LIST_SUCCESS = '@phrasebook/FETCH_PHRASE_LIST_SUCCESS',

  DELETE_PHRASE_REQUESTED = '@phrasebook/DELETE_PHRASE_REQUESTED',
  DELETE_PHRASE_LOADING = '@phrasebook/DELETE_PHRASE_LOADING',
  DELETE_PHRASE_FAILURE = '@phrasebook/DELETE_PHRASE_FAILURE',
  DELETE_PHRASE_SUCCESS = '@phrasebook/DELETE_PHRASE_SUCCESS',

  SET_PHRASE_FORM_IS_DIRTY = '@phrasebook/SET_PHRASE_FORM_IS_DIRTY',
}
